---
driver:
  name: vagrant
  
provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_diff: true
  roles_path: ../../roles
  playbook: ../../playbook.yml
  require_chef_for_busser: true
  requirements_path: requirements.yml
  
platforms:
  - name: ubuntu-16.04
    # lifecycle:
    #   pre_verify:
    #     - remote: sudo apt-get -y install python-pip

suites:
  - name: default