---
driver:
  name: vagrant
  
provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_diff: true
  roles_path: ../../roles
  playbook: ../../playbook.yml
  require_chef_for_busser: false
  requirements_path: requirements.yml
  
verifier:
  name: shell
  command: >
    py.test --color=yes
    --host="paramiko://${KITCHEN_USERNAME}@${KITCHEN_HOSTNAME}:${KITCHEN_PORT}?ssh_identity_file=${KITCHEN_SSH_KEY}"
    "test/integration/${KITCHEN_SUITE}"

platforms:
  - name: centos-7.2
    transport:
      max_ssh_sessions: 6

suites:
  - name: default